#!/usr/bin/env bash
# This script configures localhost and facebook.com IP addresses

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
